### ISSUE TITLE
[AVM Module Issue]: modtm provider not available

### ISSUE THREAD

**Issue by Pavkum007** [Azure/terraform-azurerm-avm-res-recoveryservices-vault#35]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Need to add modtm provider information in terraform.tf file so that it can pick it up from azurerm instead of hashicorp/modtm

modtm = {
      source  = "azure/modtm"
      version = "~> 0.3"
    }

**Comment by elsalvos** [comment]
looking into addressing this issue.

**Comment by elsalvos** [comment]
added recommendation
https://github.com/Azure/terraform-azurerm-avm-res-recoveryservices-vault/pull/36
